# Generated by Django 5.0.7 on 2024-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0002_alter_customuser_date_of_birth_alter_records_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
